"""phase1_medical_rebrand_remove_ecommerce

Revision ID: 37a6ad5f6b73
Revises: a1b2c3d4e5f6
Create Date: 2026-05-31 16:58:39.149030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '37a6ad5f6b73'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('consent_status', sa.String(length=16), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_catalog_variants_product_id'), table_name='catalog_variants')
    op.drop_index(op.f('ix_catalog_variants_tenant_id'), table_name='catalog_variants')
    op.drop_table('catalog_variants')
    op.drop_index(op.f('ix_payment_failures_customer_id'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_invoice_id'), table_name='payment_failures')
    op.drop_index(op.f('ix_payment_failures_tenant_id'), table_name='payment_failures')
    op.drop_table('payment_failures')
    op.drop_index(op.f('ix_product_catalog_tenant_id'), table_name='product_catalog')
    op.drop_table('product_catalog')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_compatibility_tenant_id'), table_name='compatibility')
    op.drop_table('compatibility')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_escalations_customer_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_tenant_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_workflow_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_policy_sets_tenant_id'), table_name='policy_sets')
    op.drop_table('policy_sets')
    op.alter_column('ai_interactions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ai_interactions', 'workflow_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ai_interactions', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('api_keys', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('canned_responses', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('canned_responses', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('canonical_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('canonical_events', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('channels_config', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('channels_config', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_logs', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chat_logs', 'session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('communications', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('communications', 'workflow_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('communications', 'customer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('communications', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversation_ratings', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversation_ratings', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversation_ratings', 'message_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('conversations', sa.Column('workflow_state', sa.String(length=64), nullable=True))
    op.alter_column('conversations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('conversations', 'workflow_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_conversations_workflow_id'), 'conversations', ['workflow_id'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'escalation_id')
    op.add_column('customers', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('total_conversations', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('total_workflows', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('customers', 'shopify_customer_id')
    op.drop_column('customers', 'risk_level')
    op.drop_column('customers', 'recharge_customer_id')
    op.drop_column('customers', 'stripe_customer_id')
    op.drop_column('customers', 'frustration_score')
    op.drop_column('customers', 'sentiment_state')
    op.alter_column('files', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('files', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'workflow_id')
    op.drop_column('messages', 'workflow_state')
    op.alter_column('native_connectors', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('native_connectors', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'conversation_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.alter_column('timeline_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('timeline_events', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('webhook_configs', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('workflow_transitions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('workflow_transitions', 'workflow_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('workflows', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('workflows', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('workflow_transitions', 'workflow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('workflow_transitions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('webhook_configs', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('timeline_events', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('timeline_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=False)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('operator_notes', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('native_connectors', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('native_connectors', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('messages', sa.Column('workflow_state', sa.VARCHAR(length=64), nullable=True))
    op.add_column('messages', sa.Column('workflow_id', sa.NUMERIC(), nullable=True))
    op.create_foreign_key(None, 'messages', 'workflows', ['workflow_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('files', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('files', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('customers', sa.Column('sentiment_state', sa.VARCHAR(length=32), nullable=True))
    op.add_column('customers', sa.Column('frustration_score', sa.INTEGER(), nullable=True))
    op.add_column('customers', sa.Column('stripe_customer_id', sa.TEXT(), nullable=True))
    op.add_column('customers', sa.Column('recharge_customer_id', sa.TEXT(), nullable=True))
    op.add_column('customers', sa.Column('risk_level', sa.VARCHAR(length=32), nullable=True))
    op.add_column('customers', sa.Column('shopify_customer_id', sa.TEXT(), nullable=True))
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('customers', 'last_message_at')
    op.drop_column('customers', 'total_workflows')
    op.drop_column('customers', 'total_conversations')
    op.drop_column('customers', 'tags')
    op.add_column('conversations', sa.Column('escalation_id', sa.NUMERIC(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'escalations', ['escalation_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'workflows', ['workflow_id'], ['id'])
    op.drop_index(op.f('ix_conversations_workflow_id'), table_name='conversations')
    op.alter_column('conversations', 'workflow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('conversations', 'workflow_state')
    op.alter_column('conversation_ratings', 'message_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('conversation_ratings', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('conversation_ratings', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('communications', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('communications', 'customer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('communications', 'workflow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('communications', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_logs', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('chat_logs', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('channels_config', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('channels_config', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('canonical_events', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('canonical_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('canned_responses', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('canned_responses', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ai_interactions', 'tenant_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ai_interactions', 'workflow_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('ai_interactions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('policy_sets',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('retry_policy', sqlite.JSON(), nullable=True),
    sa.Column('communication_policy', sqlite.JSON(), nullable=True),
    sa.Column('escalation_policy', sqlite.JSON(), nullable=True),
    sa.Column('approval_policy', sqlite.JSON(), nullable=True),
    sa.Column('enabled_workflows', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('wismo_policy', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_sets_tenant_id'), 'policy_sets', ['tenant_id'], unique=1)
    op.create_table('escalations',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('workflow_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('escalation_reason', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=16), nullable=True),
    sa.Column('owner_id', sa.TEXT(), nullable=True),
    sa.Column('assigned_to', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), nullable=True),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=True),
    sa.Column('sla_breached', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_workflow_id'), 'escalations', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_escalations_tenant_id'), 'escalations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_escalations_customer_id'), 'escalations', ['customer_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('escalation_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('approval_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('workflow_failure_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('daily_summary', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=1)
    op.create_table('compatibility',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('source_product_id', sa.TEXT(), nullable=False),
    sa.Column('source_product_name', sa.TEXT(), nullable=True),
    sa.Column('target_product_id', sa.TEXT(), nullable=False),
    sa.Column('target_product_name', sa.TEXT(), nullable=True),
    sa.Column('relationship', sa.VARCHAR(length=32), nullable=True),
    sa.Column('condition', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_tenant_id'), 'compatibility', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('external_subscription_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('plan_name', sa.TEXT(), nullable=True),
    sa.Column('product_sku', sa.TEXT(), nullable=True),
    sa.Column('renewal_date', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('pause_state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('skip_state', sa.VARCHAR(length=32), nullable=True),
    sa.Column('mrr', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('subscription_id', sa.NUMERIC(), nullable=True),
    sa.Column('external_invoice_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('amount_due', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('payment_attempt_count', sa.INTEGER(), nullable=True),
    sa.Column('last_failure_reason', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_table('product_catalog',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('product_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('attributes', sqlite.JSON(), nullable=True),
    sa.Column('stock_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('product_url', sa.TEXT(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('import_batch', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_catalog_tenant_id'), 'product_catalog', ['tenant_id'], unique=False)
    op.create_table('payment_failures',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('invoice_id', sa.NUMERIC(), nullable=False),
    sa.Column('subscription_id', sa.NUMERIC(), nullable=True),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('failure_type', sa.TEXT(), nullable=True),
    sa.Column('failure_category', sa.TEXT(), nullable=True),
    sa.Column('recoverability', sa.VARCHAR(length=32), nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), nullable=True),
    sa.Column('detected_at', sa.DATETIME(), nullable=False),
    sa.Column('last_retry_at', sa.DATETIME(), nullable=True),
    sa.Column('workflow_id', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_failures_tenant_id'), 'payment_failures', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payment_failures_invoice_id'), 'payment_failures', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_failures_customer_id'), 'payment_failures', ['customer_id'], unique=False)
    op.create_table('catalog_variants',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('tenant_id', sa.NUMERIC(), nullable=False),
    sa.Column('product_id', sa.NUMERIC(), nullable=False),
    sa.Column('sku', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('attributes', sqlite.JSON(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('stock_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_variants_tenant_id'), 'catalog_variants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_catalog_variants_product_id'), 'catalog_variants', ['product_id'], unique=False)
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
